name: Wails Build Action for MacOS

inputs:
  build-name:
    description: Build name
    type: string
  build-platform:
    description: Platform to build for
    type: string

runs:
  using: composite
  steps:
    - name: Prepare build environment
      uses: ./.github/release/prepare
    - name: Build app
      run: wails build --platform ${{ inputs.build-platform }} -webview2 download -o api-client
      shell: bash
    - name: Fix permission
      run: chmod +x build/bin/*/Contents/MacOS/*
      shell: bash
    - name: package build
      run: productbuild --component ./build/bin/api-client.app /Applications ./build/bin/${{inputs.build-name}}.pkg
      shell: bash
    - name: Handle artifacts
      uses: ./.github/release/artifact
      with:
        build-name: ${{ inputs.build-name }}
