name: Testing Pipeline
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  Go-Test:
    name: "Go Test"
    strategy:
      max-parallel: 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check version of go
        run: go version

      - name: Install dependencies
        run: make install-backend-dependencies

      - name: Run tests
        run: make test-backend
