name: "Wails Prepare Action for Linux, Windows, MacOS"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: 'frontend/package.json'
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      shell: bash
