// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function AddHeader(arg1:frontend.EnvironmentHeaderDTO,arg2:frontend.EnvironmentDTO):Promise<frontend.EnvironmentHeaderDTO>;

export function Create(arg1:frontend.EnvironmentDTO):Promise<frontend.EnvironmentDTO>;

export function Delete(arg1:frontend.EnvironmentDTO):Promise<void>;

export function GetAll():Promise<Array<frontend.EnvironmentDTO>>;

export function RemoveHeader(arg1:frontend.EnvironmentHeaderDTO):Promise<void>;

export function Update(arg1:frontend.EnvironmentDTO):Promise<frontend.EnvironmentDTO>;

export function UpdateHeader(arg1:frontend.EnvironmentHeaderDTO):Promise<frontend.EnvironmentHeaderDTO>;
