// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHeader(arg1, arg2) {
  return window['go']['frontend']['Environment']['AddHeader'](arg1, arg2);
}

export function Create(arg1) {
  return window['go']['frontend']['Environment']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['frontend']['Environment']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['frontend']['Environment']['GetAll']();
}

export function RemoveHeader(arg1) {
  return window['go']['frontend']['Environment']['RemoveHeader'](arg1);
}

export function Update(arg1) {
  return window['go']['frontend']['Environment']['Update'](arg1);
}

export function UpdateHeader(arg1) {
  return window['go']['frontend']['Environment']['UpdateHeader'](arg1);
}
