// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function AddDisabledHeader(arg1:frontend.EnvironmentHeaderDTO,arg2:frontend.HttpRequestDto):Promise<void>;

export function AddHeader(arg1:frontend.HttpRequestHeaderDto,arg2:frontend.HttpRequestDto):Promise<frontend.HttpRequestHeaderDto>;

export function AddParameter(arg1:frontend.HttpRequestParameterDto,arg2:frontend.HttpRequestDto):Promise<frontend.HttpRequestParameterDto>;

export function Create(arg1:frontend.HttpRequestDto):Promise<frontend.HttpRequestDto>;

export function Delete(arg1:frontend.HttpRequestDto):Promise<void>;

export function GetAll():Promise<Array<frontend.HttpRequestDto>>;

export function RemoveDisabledHeader(arg1:frontend.EnvironmentHeaderDTO,arg2:frontend.HttpRequestDto):Promise<void>;

export function RemoveHeader(arg1:frontend.HttpRequestHeaderDto):Promise<void>;

export function RemoveParameter(arg1:frontend.HttpRequestParameterDto):Promise<void>;

export function Update(arg1:frontend.HttpRequestDto):Promise<frontend.HttpRequestDto>;

export function UpdateHeader(arg1:frontend.HttpRequestHeaderDto):Promise<frontend.HttpRequestHeaderDto>;

export function UpdateParameter(arg1:frontend.HttpRequestParameterDto):Promise<frontend.HttpRequestParameterDto>;
