// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDisabledHeader(arg1, arg2) {
  return window['go']['frontend']['HttpRequests']['AddDisabledHeader'](arg1, arg2);
}

export function AddHeader(arg1, arg2) {
  return window['go']['frontend']['HttpRequests']['AddHeader'](arg1, arg2);
}

export function AddParameter(arg1, arg2) {
  return window['go']['frontend']['HttpRequests']['AddParameter'](arg1, arg2);
}

export function Create(arg1) {
  return window['go']['frontend']['HttpRequests']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['frontend']['HttpRequests']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['frontend']['HttpRequests']['GetAll']();
}

export function RemoveDisabledHeader(arg1, arg2) {
  return window['go']['frontend']['HttpRequests']['RemoveDisabledHeader'](arg1, arg2);
}

export function RemoveHeader(arg1) {
  return window['go']['frontend']['HttpRequests']['RemoveHeader'](arg1);
}

export function RemoveParameter(arg1) {
  return window['go']['frontend']['HttpRequests']['RemoveParameter'](arg1);
}

export function Update(arg1) {
  return window['go']['frontend']['HttpRequests']['Update'](arg1);
}

export function UpdateHeader(arg1) {
  return window['go']['frontend']['HttpRequests']['UpdateHeader'](arg1);
}

export function UpdateParameter(arg1) {
  return window['go']['frontend']['HttpRequests']['UpdateParameter'](arg1);
}
