name: Wails build

on:
  workflow_dispatch:
  release:
    types: [ created ]

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "api-client-linux-amd64"
            platform: linux/amd64
          - name: "api-client-linux-arm64"
            platform: linux/arm64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build linux
        uses: ./.github/release/linux
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
#  build:
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - name: "api-client-linux-amd64"
#            platform: linux/amd64
#            os: ubuntu-22.04
#          - name: "api-client-linux-arm64"
#            platform: linux/arm64
#            os: ubuntu-22.04
#          - name: "api-client-windows-amd64"
#            platform: windows/amd64
#            os: windows-latest
#          - name: "api-client-windows-arm64"
#            platform: windows/arm64
#            os: windows-latest
#          - name: "api-client-macos-amd64"
#            platform: darwin/amd64
#            os: macos-latest
#          - name: "api-client-macos-arm64"
#            platform: darwin/arm64
#            os: macos-latest
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - name: Build wails
#        uses: dAppServer/wails-build-action@v2.2
#        id: build
#        with:
#          build-name: ${{ matrix.name }}
#          build-platform: ${{ matrix.platform }}
#          package: true
#          go-version: "1.23"
#          node-version: "20.18.0"


