name: Wails build

on:
  workflow_dispatch:
  release:
    types: [ created ]

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api-client-linux-amd64-gtk4.0
            platform: linux/amd64
            libwebkitversion: libwebkit2gtk-4.0-dev
            os: ubuntu-22.04
            tag: ''
          - name: api-client-linux-arm64-gtk4.0
            platform: linux/arm64
            libwebkitversion: libwebkit2gtk-4.0-dev
            os: ubuntu-22.04-arm
            tag: ''
          - name: api-client-linux-amd64-gtk4.1
            platform: linux/amd64
            libwebkitversion: libwebkit2gtk-4.1-dev
            os: ubuntu-24.04
            tag: -tags webkit2_41
          - name: api-client-linux-arm64-gtk4.1
            platform: linux/arm64
            libwebkitversion: libwebkit2gtk-4.1-dev
            os: ubuntu-24.04-arm
            tag: -tags webkit2_41

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build on linux
        uses: ./.github/release/linux
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api-client-windows-amd64
            platform: windows/amd64
          - name: api-client-windows-arm64
            platform: windows/arm64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build on windows
        uses: ./.github/release/windows
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api-client-macos-universal
            platform: darwin/universal
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build on macos
        uses: ./.github/release/macos
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
